# Generated by Django 3.1.3 on 2020-11-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('L', 'Lentes'), ('G', 'Gotas'), ('P', 'Pastillas')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('P', 'Pendiente'), ('O', 'Pedido'), ('T', 'Taller'), ('F', 'Finalizado')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Rol2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('S', 'Secretaria'), ('M', 'Profesional medico'), ('V', 'Ventas'), ('T', 'Taller'), ('G', 'Gerencia')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('T', 'Tarjeta Credito'), ('D', 'Debito'), ('V', 'Billetera Virtual'), ('E', 'Efectivo')], max_length=1)),
            ],
        ),
    ]
