# Generated by Django 3.1.3 on 2020-11-28 19:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('pacientepresente', models.BooleanField(default=False)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoturno', to='clinica.personal')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacienteturno', to='clinica.paciente')),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretariaturno', to='clinica.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('laboratorio', models.CharField(max_length=50)),
                ('lejos', models.BooleanField()),
                ('izquierda', models.BooleanField()),
                ('armazon', models.BooleanField()),
                ('precio', models.FloatField()),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipoproducto', to='clinica.clasificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadox', to='clinica.estadopedido')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientex', to='clinica.paciente')),
                ('tipoPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipopagox', to='clinica.tipopago')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedorx', to='clinica.personal')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('cantidad', models.IntegerField()),
                ('total', models.FloatField()),
                ('lejos', models.BooleanField(default=False)),
                ('izquierda', models.BooleanField(default=False)),
                ('armazon', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientex2', to='clinica.paciente')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidositem', to='clinica.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productoitem', to='clinica.producto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedorx2', to='clinica.personal')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(max_length=255)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicos', to='clinica.personal')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='clinica.paciente')),
            ],
        ),
    ]
